language: python
python:
  - 3.6

cache: pip

install:
  - pip install -e .
  - pip install tensorflow
  - pip install coverage

script:
  - nosetests -v --with-coverage --cover-tests --cover-package=nara_wpe tests/*
